In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('attacks.csv')
df

,Unnamed: 0,Case Number,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,1,2018.06.18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2,2018.06.09,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,3,2018.06.08,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,4,2018.06.04,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6109,6127,1804.02.26.R,1804.0,Boat,AUSTRALIA,New South Wales,"Georges Head, off Port Jackson",NaN,boat,NaN,...,NaN,"Sydney Gazette, 2/26/1804",1804.02.26-boat-GeorgesHead.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1804.02.26.R,1804.02.26.R,176.0,NaN,NaN
6110,6128,1803.05.17,1803.0,Sea Disaster,USA,South Carolina,Off Charleston,NaN,Captain Jones,M,...,NaN,"Evening Post, 6/13/1803",1803.05.17-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.05.17,1803.05.17,175.0,NaN,NaN
6111,6129,1803.03.00,1803.0,Unprovoked,AUSTRALIA,Western Australia,"Hamelin Harbour, at Faure Island",NaN,M. Lefevre & a sailor (rescuer),M,...,NaN,F. Peron ref in G.P. Whitley (Fishes of Austr...,1803.03.00-Lefevre.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.03.00,1803.03.00,174.0,NaN,NaN
6112,6130,1802.04.13.R,1802.0,Unprovoked,INDIA,NaN,NaN,NaN,NaN,NaN,...,NaN,Evening Post (New York) 4/13/1802,1802.04.13.R-India.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1802.04.13.R,1802.04.13.R,173.0,NaN,NaN
6113,6131,1801.12.18.R,1801.0,Provoked,NaN,NaN,NaN,Standing on landed shark's tail,Stephen Pettigew,N,...,12' shark,"The Evening Post, 12/18/1801",1801.12.18.R-Pettigrew.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1801.12.18.R,1801.12.18.R,172.0,NaN,NaN

Â¿CuÃ¡ntas filas y columnas tiene el DataFrame?

In [6]:

shape_df= df.shape
print(f'El DataFrame tiene {shape_df[0]} filas y {shape_df[1]} columnas')

El DataFrame tiene 6114 filas y 22 columnas

Mostrad las primeras cinco filas y las Ãºltimas cinco filas del DataFrame.

In [7]:
print('Las primeras 5 filas son:')
df.head()

Las primeras 5 filas son:

,Unnamed: 0,Case Number,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,1,2018.06.18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2,2018.06.09,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,3,2018.06.08,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,4,2018.06.04,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [8]:
print('Las Ãºltimas 5 filas son:')
df.tail()

Las Ãºltimas 5 filas son:

,Unnamed: 0,Case Number,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
6109,6127,1804.02.26.R,1804.0,Boat,AUSTRALIA,New South Wales,"Georges Head, off Port Jackson",NaN,boat,NaN,...,NaN,"Sydney Gazette, 2/26/1804",1804.02.26-boat-GeorgesHead.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1804.02.26.R,1804.02.26.R,176.0,NaN,NaN
6110,6128,1803.05.17,1803.0,Sea Disaster,USA,South Carolina,Off Charleston,NaN,Captain Jones,M,...,NaN,"Evening Post, 6/13/1803",1803.05.17-Jones.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.05.17,1803.05.17,175.0,NaN,NaN
6111,6129,1803.03.00,1803.0,Unprovoked,AUSTRALIA,Western Australia,"Hamelin Harbour, at Faure Island",NaN,M. Lefevre & a sailor (rescuer),M,...,NaN,F. Peron ref in G.P. Whitley (Fishes of Austr...,1803.03.00-Lefevre.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.03.00,1803.03.00,174.0,NaN,NaN
6112,6130,1802.04.13.R,1802.0,Unprovoked,INDIA,NaN,NaN,NaN,NaN,NaN,...,NaN,Evening Post (New York) 4/13/1802,1802.04.13.R-India.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1802.04.13.R,1802.04.13.R,173.0,NaN,NaN
6113,6131,1801.12.18.R,1801.0,Provoked,NaN,NaN,NaN,Standing on landed shark's tail,Stephen Pettigew,N,...,12' shark,"The Evening Post, 12/18/1801",1801.12.18.R-Pettigrew.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1801.12.18.R,1801.12.18.R,172.0,NaN,NaN

Mostrad 2 filas al azar del DataFrame.

In [9]:
print('Mostramos dos filas al azar:')
df.sample(2)

Mostramos dos filas al azar:

,Unnamed: 0,Case Number,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
83,83,2017.09.16.a,2017.0,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/16/2017",2017.09.16.a-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.16.a,2017.09.16.a,6220.0,NaN,NaN
1773,1780,2003.04.23.b,2003.0,Unprovoked,BRAZIL,Pernambuco,"Pau Amarelo Beach, Paulista District (17 km fr...",Surfing,Tiago Augusto da Silva Machado,M,...,Bull shark,"P. M. Lopes, GSAF; N. Souza da Silva; JC, 4/24...",2003.04.23.b-Machado.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.04.23.b,2003.04.23.b,4523.0,NaN,NaN

Â¿CuÃ¡l es el nombre de las columnas del DataFrame?

In [10]:
print('Los nombres de las columnas son:')
columnas_df = df.columns
columnas_df

Los nombres de las columnas son:

Index(['Unnamed: 0', 'Case Number', 'Year', 'Type', 'Country', 'Area',
       'Location', 'Activity', 'Name', 'Sex ', 'Age', 'Time', 'Species ',
       'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

Â¿CuÃ¡les son los principales estÃ¡disticos del DataFrame? Mostrad por separado las variables categÃ³ricas y las variables numÃ©ricas.

In [11]:
print('Las principales estadÃ­sticas de variables numÃ©ricas son: ')
df.describe()

Las principales estadÃ­sticas de variables numÃ©ricas son:

        Unnamed: 0         Year  original order
count  6114.000000  6114.000000     6114.000000
mean   3065.554629  1968.831207     3237.445044
std    1769.652139    43.745920     1769.652633
min       0.000000  1801.000000      172.000000
25%    1534.250000  1946.000000     1706.250000
50%    3066.500000  1980.000000     3236.500000
75%    4596.750000  2005.000000     4768.750000
max    6131.000000  2018.000000     6303.000000

In [12]:
print('Las principales estadÃ­sticas de variables categÃ³ricas son: ')
df.describe(include='object')

Las principales estadÃ­sticas de variables categÃ³ricas son:

,Case Number,Type,Country,Area,Location,Activity,Name,Sex,Age,Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,Unnamed: 22,Unnamed: 23
count,6113,6110,6074,5706,5626,5603,5914,5564,3448,2934,3409,6098,6114,6113,6114,6114,6114,1,2
unique,6113,8,201,791,4020,1484,5118,6,156,366,1529,4837,6105,6104,6099,6113,6114,1,2
top,2018.06.25,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,17,Afternoon,White shark,"C. Moore, GSAF",1898.00.00.R-Syria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.08.04,2018.06.25,stopped here,Teramo
freq,1,4438,2200,1025,162,966,511,4939,154,183,161,95,2,2,4,2,1,1,1

Â¿CuÃ¡l es el porcentaje de valores nulos en cada columna?

In [13]:
nul = df.isnull().sum()
nul

Unnamed: 0                   0
Case Number                  1
Year                         0
Type                         4
Country                     40
Area                       408
Location                   488
Activity                   511
Name                       200
Sex                        550
Age                       2666
Time                      3180
Species                   2705
Investigator or Source      16
pdf                          0
href formula                 1
href                         0
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               6113
Unnamed: 23               6112
dtype: int64

In [14]:
nul.size

22

In [15]:
lista = []
for i in range(nul.size):
    
    
    porcentaje = nul[i]*100/6114
    lista.append(round(porcentaje, 2))

    
print(lista)

[0.0, 0.02, 0.0, 0.07, 0.65, 6.67, 7.98, 8.36, 3.27, 9.0, 43.6, 52.01, 44.24, 0.26, 0.0, 0.02, 0.0, 0.0, 0.0, 0.0, 99.98, 99.97]

Sacad los valores Ãºnicos y su frecuencia de las variables numÃ©ricas. Almacenad los resultados en un diccionario. Uno para cada variable.

In [16]:
valores_unicos = {}
for i in columnas_df:

    valores_unicos.update({i:df[i].unique()})

valores_unicos

{'Unnamed: 0': array([   0,    1,    2, ..., 6129, 6130, 6131]),
 'Case Number': array(['2018.06.25', '2018.06.18', '2018.06.09', ..., '1803.03.00',
        '1802.04.13.R', '1801.12.18.R'], dtype=object),
 'Year': array([2018., 2017., 2016., 2015., 2014., 2013., 2012., 2011., 2010.,
        2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002., 2001.,
        2000., 1999., 1998., 1997., 1996., 1995., 1984., 1994., 1993.,
        1992., 1991., 1990., 1989., 1969., 1988., 1987., 1986., 1985.,
        1983., 1982., 1981., 1980., 1979., 1978., 1977., 1976., 1975.,
        1974., 1973., 1972., 1971., 1970., 1968., 1967., 1966., 1965.,
        1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957., 1956.,
        1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948., 1848.,
        1947., 1946., 1945., 1944., 1943., 1942., 1941., 1940., 1939.,
        1938., 1937., 1936., 1935., 1934., 1933., 1932., 1931., 1930.,
        1929., 1928., 1927., 1926., 1925., 1924., 1923., 1922., 1921.,
        1920., 1919., 1918., 1917., 1916., 1915., 1914., 1913., 1912.,
        1911., 1910., 1909., 1908., 1907., 1906., 1905., 1904., 1903.,
        1902., 1901., 1900., 1899., 1898., 1897., 1896., 1895., 1894.,
        1893., 1892., 1891., 1890., 1889., 1888., 1887., 1886., 1885.,
        1884., 1883., 1882., 1881., 1880., 1879., 1878., 1877., 1876.,
        1875., 1874., 1873., 1872., 1871., 1870., 1869., 1868., 1867.,
        1866., 1865., 1864., 1863., 1862., 1861., 1860., 1859., 1858.,
        1857., 1856., 1855., 1853., 1852., 1851., 1850., 1849., 1847.,
        1846., 1845., 1844., 1842., 1841., 1840., 1839., 1837., 1836.,
        1835., 1834., 1832., 1831., 1830., 1829., 1828., 1827., 1826.,
        1825., 1823., 1822., 1819., 1818., 1817., 1816., 1815., 1812.,
        1811., 1810., 1808., 1807., 1805., 1804., 1803., 1802., 1801.]),
 'Type': array(['Boating', 'Unprovoked', 'Invalid', 'Provoked', 'Questionable',
        'Sea Disaster', nan, 'Boat', 'Boatomg'], dtype=object),
 'Country': array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
        'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'NEW CALEDONIA',
        'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
        'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
        'EGYPT', 'ST HELENA, British overseas territory', 'COMOROS',
        'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
        'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
        'COLUMBIA', 'CAPE VERDE', 'Fiji', 'DOMINICAN REPUBLIC',
        'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'FIJI', 'PUERTO RICO',
        'ITALY', 'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
        'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
        'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
        'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
        'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
        'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
        'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
        'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
        'YEMEN', 'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN',
        'GRAND CAYMAN', 'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ',
        'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
        'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
        'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
        'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
        'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN', 'PORTUGAL',
        'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
        'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
        'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
        'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
        'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
        'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
        'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA / INDIAN OCEAN',
        'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
        'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
        'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'ARGENTINA',
        'MARTINIQUE', 'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
        'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', 'SIERRA LEONE',
        ' PHILIPPINES', 'NICARAGUA', 'CENTRAL PACIFIC',
        'SOLOMON ISLANDS / VANUATU', 'SOUTHWEST PACIFIC OCEAN',
        'BAY OF BENGAL', 'MID-PACIFC OCEAN', 'SLOVENIA', 'CURACAO',
        'ICELAND', 'ITALY / CROATIA', 'BARBADOS', 'HONDURAS', 'MONACO',
        'GUYANA', 'HAITI', 'SAN DOMINGO', 'IRELAND', 'KUWAIT', 'YEMEN ',
        'REUNION ISLAND', 'FALKLAND ISLANDS', 'CRETE', 'CYPRUS', 'EGYPT ',
        'WEST INDIES', 'BURMA', 'LEBANON', 'PARAGUAY',
        'BRITISH NEW GUINEA', 'CEYLON', 'OCEAN', 'GEORGIA', 'SYRIA',
        'TUVALU', 'INDIAN OCEAN?', 'GUINEA', 'ANDAMAN ISLANDS',
        'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
        'AFRICA', 'ALGERIA', 'Coast of AFRICA', 'TASMAN SEA', 'GHANA'],
       dtype=object),
 'Area': array(['California', 'Georgia', 'Hawaii', 'New South Wales', 'Colima',
        'Pernambuco', 'Florida', 'Queensland', 'South Carolina',
        'Cornwall', 'Westerm Australia', 'Eastern Cape Province',
        'Hua Hin', 'Cocos Island', 'Western Australia',
        'Alifu Alifu Atoll', 'Western Cape Province', 'New Providence',
        'Alagoas', nan, 'Victoria', 'KwaZulu-Natal',
        'Boi Island, Victoria', 'Galapagos Islands', 'Fernando de Noronha',
        'Sepang', 'Holquin Province', 'Pamplemousses ', 'South Australia',
        'North Island', 'New York', 'Canary Islands', ' Upolu Island',
        'Shizuoka Prefecture', 'Texas', 'CastellÃ³n', 'Massachusetts',
        'Red Sea Protectorate', 'New Providence District',
        '40 miles off Grand Bahama Island', 'Ascension Island',
        'New Jersey', 'Majorca', 'Washington', 'Tabasco', 'Anjouan',
        'Ibiza Island', 'Marquesas', 'South Devon', 'New Providence ',
        'Sharjah, ', 'Baja California Sur', 'Saint-Leu', 'South Island',
        'Luzon Island', 'Great Exuma', 'Saint-Andre', 'Bimini', 'Bali',
        'Tuamotos', 'Oregon', 'North Province', 'New Providence Island',
        'Alicante Province', 'Hong Kong', 'Kochi Prefecture', 'Tasmania',
        'Abaco Islands', 'Alabama', 'North Carolina', 'Isla Provedencia',
        'Suez', 'Grand Terre', 'Boa Vista Island', 'Vanua Levu',
        'Santa Catarina State', 'South Province', 'Altagracia Province',
        'Grand Cayman', 'BalneÃ¡rio CamboriÃº', 'Fujairah Emirate',
        'Grand Canary Island', 'Inhambane Province', 'Phuket', 'Alicante',
        'Guanacaste', 'Bora Bora', 'Grand Bahama Island', 'Le Port',
        'Rangiroa', 'Saint-Gilles-les-Bains', 'Sardinia', 'Sinaloa',
        'Central Tuamotu', 'd\x92Ãtang-SalÃ©', 'Granada',
        'Cargados Carajos Shoals (St. Brandon)', 'Moorea', 'Catalonia',
        'Maryland', 'Louisiana', 'West End', 'Delaware',
        'Atsumi peninsula', 'Palmyra Atoll', 'Wallis and Futuna',
        'Baie de Sainte-Marie', 'Society Islands', 'Trinidad',
        'Okinawa Prefecture', '740 miles SE of Tarawa Atoll',
        'Southern District', 'Bay of Biscay', 'Quintana Roo',
        'Exuma Islands', 'Saint-Paul', 'Taitung ', 'Kingston Parish',
        'Santa Cruz Island', 'Saint-Gilles', 'Tuamotus', 'Eleuthera',
        'St. Catherine', 'Palawan', 'Mercury Islands', 'Delta', "Vava'u",
        'Inner Hebrides', 'Saint Leu', 'Trois-Bassins', 'British Colombia',
        'Guerrero', 'Saint-Benoit', 'Tabuk Province',
        'Antofagasta Province', "St John's", 'Santa Elena',
        'East New Britain', 'Bois-Blanc ', 'Moray', 'Puerto Rico',
        'SamanÃ¡ Province', 'Coast Province', 'Central Province',
        'Primorsky Krai',
        'Peter the Great Bay, Khasan, Primorsky Krai (Far East)',
        'Telyakovsky Bay, Khasan,  Primorsky Krai (Far East)', 'Praslin',
        'Sucre', 'Middle Caicos', 'Caicos Bank', 'San AndrÃ©s archipelago',
        'Kedah', 'Umm al Qaywayan Province', 'Vitu Levu',
        'South Sinai Peninsula', ' Loyalty Islands', 'Saint Gilles ',
        'Maine', 'Virginia', "Ha'api ", 'Western Province',
        'Jeju Province', 'Binh Dinh Province', 'Antsiranana Province',
        'Sinai Peninsula', 'Off Vanua Levu', 'Merizo', 'Rio Grande Do Sul',
        'Dubai', 'Torres Strait', 'Eastern Province',
        'Eastern Cape  Province', 'Maputo Province', 'Bocas', 'Fife',
        'Devon', 'Makira-Ulawa Province', 'Mombasa', 'Catalunya',
        'St. Johns Reef', 'Off Green Island', 'North Region',
        'Batangas province', 'Strait of Malacca', 'Guantanamo Province',
        'MaranhÃ£o', 'Red Sea', 'Batanes Provine', 'Luzon',
        'Northern Territory', ' Split-Dalmatia Count,', 'North Devon',
        'US Virgin Islands', 'San Carlos', 'Cabo San Lucas', 'Sussex',
        'Bahia', 'Easter Ross', 'Guerro', 'Yasawa Islands',
        'Northern Bahamas', 'Tokyo Bay', 'Baja California', 'Green Bay',
        'Loyalty Islands', 'Marovo Lagoon',
        'Territory of Cocos (Keeling) Islands', 'Oslo Fjord', 'Kent',
        'Bird Island', 'Providenciales', 'Bimini Islands',
        'Muhafazat Hadramawt', 'Cook islans', 'Surigao del Norte',
        'Between Somalia & Yemen', 'Ambergris Caye', 'Saint-Pierre',
        'Kentucky', 'Andros Islands', 'Guam', 'Western Area',
        '300 miles from Antigua', '800 miles from land',
        '600 nm west of the Canary Islands', 'Simpson Bay', 'East Wall',
        'Inner Islands', 'Shanghai', 'Malampa Province',
        "South Ch'ungch'ong Province", 'New Mexico',
        'Santa Isabel Province', 'Santiago de Cuba Province',
        'Camaguey Province', 'ConservatÃ³ria District', 'South Carolina ',
        'Kuril Islands in the Pacific', 'Wakayama Prefecture',
        "Nuku'alofa", 'Saint-BenoÃ®t',
        'South Island, near Karitane north of Dunedin', 'Rocha',
        'Northlands', 'Anzoategui', 'Cook Islands', 'Tamil Nadu',
        'Pearl Islands', 'Taveuni', 'Johnston Atoll', 'Baatan',
        'Rio de Janeiro', 'Nueva Esparta', 'Southland',
        'North Pacific coast', 'Caroline Islands', 'Cheshire',
        'Louisiade Archipelago',
        'KwaZulu-Natal between Port Edward and Port St Johns',
        'Milne Bay Province', 'Cikobia Island (north of Vanua Levu)',
        'Rayong Province', 'Zamboanga del Sur Province',
        'Rio Grande de Norte',
        'Off the western coast of peninsular Malaysia', 'New Brunswick',
        'Miyako Island', 'Alaska', 'Minerva Reef', 'Madang Province',
        'Worcestershire', 'Phang nga Province', 'Alinglaplap Atoll',
        'Adriatic Sea', 'Ralik Chain', 'Grand Baie',
        "L' Etang SalÃ©-les-Bains", 'Southern Japan', 'Cap Vert Peninsula',
        'Marches region', 'Berry Islands', 'Transvaal', 'Gaza',
        "Grand'Anse", 'Beaufonds', 'Miyako', "L'Etang-Sale",
        'Chatham Islands ', 'South Sinai, Gulf of Aqaba', 'Cat Cay',
        'Missouri', '12 miles off the north coast', 'Saint-Paul ',
        'Chatham Islands, east of New  Zealand', 'Saint-Denis',
        'Vava\x92u', 'Mississippi', 'Clearwater Bay', 'New Territories',
        'Aichi Prefecture', 'Tafea Province', 'Kagoshima Prefecture',
        'Saint-Joseph', 'Banaadir Region', 'La Libertad', 'Costa Blanca',
        'Walkers Cay', 'On the Kowloon penisula, south of Sai Kung',
        'Ehime Prefecture', 'Tongapatu Group', 'West Africa',
        'Wakaya Island', 'North Carolina ', 'Mexico / Caribbean Sea',
        'Antarctic Ocean', 'La Saline-les-Bains', 'Sea of Japan',
        'Tavenui', 'Ligurian Sea', "L'Etang-SalÃ©", 'Kowloon Peninsula',
        'Port Shelter', 'Laucala Island', 'Sainte-Marie',
        'Great Exuma Island', 'Sainte-Suzanne', 'Tuscany',
        'Tyrrhenian Sea', 'New Ireland', 'Valpariso Province',
        'Viscayan Sea', 'Manfredonia ', 'Tokyo Prefecture', 'Saint-Louis',
        'Mindoro', 'Between DR and Puerto Rico',
        'Between Honiara & Isabel Island', 'Florida Straits',
        'Gulf of Lyons', 'CÃ¡diz', 'Sicily', 'Andikira Fokithes',
        'Central Philippines', 'Rhode Island', 'English Channel',
        'North & South Carolina', 'Kumamoto Prefecture', 'Biserta',
        'Saint-Philippe', 'Chungnam', 'Eronogo Region', 'Coquimbo',
        'Pagasitikos Gulf', "St. Mary's Parish", 'Romblon Province',
        'Lamu Archipelago', 'Los Vilos', 'Island of Kos', "Ha'api",
        'Madeira Islands', 'Ho Ha Wan Marine Park', 'Southern Thailand',
        'Golfo de Venezia', 'Ralik Archipelago',
        'South China Sea 200 miles from Hong Kong',
        'Reggio Calabria Province', 'Mirs Bay ', 'Genoa Province',
        'Ganges-Brahmaputra delta', ' Split-Dalmatia County', 'Florida ',
        'Primorje-Gorski Kotar County ', 'Aulong Island',
        'Western Caroline Islands', 'Upolu Island', 'Antibes',
        'Illeginni Atoll', 'Istria County', 'Between Beira & Maputo',
        'Khuzestan Province', 'Inhambe Province', 'Namonuito Atoll',
        'Eastern Caroline Islands',
        'Western Caroline Islands (North Pacific Ocean)', 'Caribbean Sea',
        'St. Andrew Parish', '200 nm southeast of Manila', 'Limpopo River',
        'New Ireland Province', 'Zadar County', 'Basrah', 'Clarendon',
        'Moro Gulf', 'Johor', 'Magdalena Department', 'Mafia Island',
        'Gulf Province', 'Morobe Province', 'LimÃ³n Province',
        'Rombion Province', 'Veracruz', 'Brindisi Province',
        'Kagawa Prefecture', 'Liguria', 'Hamilton', 'Out Islands',
        'Mugla Province', 'Gibraltar', 'New Britain', 'Bay of Maputo',
        'Duke of York Islands', 'Taranto province', 'Northern Taiwan',
        'Admiralty Islands, Manus Province', 'North Sumatra',
        "250 miles southwest of O'ahu, Hawaii", 'West coast', 'East Sepik',
        'Near Bougainville (North Solomons)', 'East of the Gulf of Aqaba',
        'Bougainville (North Solomons)', 'Victoria ', 'Okayama Prefecture',
        'San Blas', 'Connecticut', 'Lau Group', 'Caribbean Coast',
        'Vita Levu', 'San Blas Islands', 'Puntarenas Province',
        'Lomaloma, Lau', 'Between Southampton & Canary Islands',
        'South Coast, East New Britain', ' Lau Province', 'Ysabel Island',
        'Santo Domingo', 'San Blas coast', 'Thessaly',
        'Lomaiviti  Island Group', 'Rodrigues', 'Manus Island',
        'Pinas Bay', 'Grand Turk Island', 'Off coast of West Africa',
        'Sharon', 'Antalya Province', 'Northern District',
        'New Ireland Province, Bismarck Archipelago', 'Cyclades',
        'Viti Levu', 'Off the Coromandel Peninsula, North Island',
        'Madang', 'Guadalcanal Province', '10ÂºS, 142ÂºE', 'Kwajalein Atoll',
        'East Flores', 'Guerrrero', 'Western Luzon Island',
        'Shefa Province', '165  miles from Bermuda',
        '25 km off the coast of Iran & 483km from mouth of Persian Gulf',
        'Venice Province', 'Sandaun Province', 'Anatolia',
        'East New Britain Province', 'United Arab Emirates',
        'Wake Island (EnenKio)', '19S, 178?E', 'Pennsylvania',
        '9.35N 79.35W', 'Roncador Bank', 'Western District',
        'Enroute from Suez to Aden (Yemen)',
        '180 miles southeast of Okinawa', 'Eniwetok Atoll',
        'Cap-Vert Peninsula', 'Delagoa Bay', 'In the English Channel ',
        'Cook Strait', 'Unknown, treated at Wick, SCOTLAND',
        'Corregidor Island', 'Paget', '33N, 68W', 'Casamance',
        'Madang (WO)', 'Between Timor & Darwin, Australia',
        'Pacific coast', 'St. Georges ', 'Eastern  Province',
        'Northwest of Viti Levu', 'West New Britain Province',
        'Rigo subdistrict', 'Masbate', '400 miles southeast of Sri Lanka',
        'Lomaiviti Province', 'Kadavu', 'Leyte Island', 'Orissa',
        'Hokkaido Prefecture', 'North Palawan', 'Queaon', 'Istria',
        'PANAMA', 'In the Gulf Stream ', 'Mersin Province', 'Guyamas',
        'Between England & South Africa', 'Mindanao',
        ' Kikori River mouth', 'South Chungcheong Province',
        'Ahirkapi coast', 'Tutuila Island', 'Primorje-Gorski Kotar County',
        'Between Hawaii & Wake Island', 'Taipei Hsien',
        'Ibaraki Prefecture', 'South Pacific Ocean', 'Canal Zone',
        '1,000 miles east of Hawaii', 'Honiara', 'Yucatan Channel',
        'Havana Province', 'Karun River',
        'Abau Subdistrict,Central Province',
        'New Britain, Bismarck Archipelago', 'Estuaire Province',
        'Near Dakar, Cap Vert Peninsula',
        'Near the Andaman & Nicobar Islands', 'Mozambique Channel',
        'Tyrrenian Sea', 'Congreve Channel', 'St. Thomas Bay', 'Madeira',
        'Between Comores & Madagascar', 'Corfu Island',
        '1000 miles west of Hawaii', 'Izo Islands',
        ' Primorje-Gorski Kotar County', 'Open sea', 'Aden',
        'New Ireland, Bismarck Archipelago', '18S / 50E', 'Illinois',
        'Isles del Rosario', 'Wake Island', 'Isle of Man',
        'Nagasaki Prefecture', 'Liguaria', 'Slovenia', 'South shore ',
        'Buenos Aires Province', '330 to 350 miles east of Wake Island',
        'Nova Scotia', 'Gulf of Panama', 'Genoa  Province',
        'Abau Sub District, Central Province', 'Teramo', 'Red Sea State',
        'Curacao', 'Port Louis Province', 'Montserrado', 'Bay of Maputu',
        'Sofala Province', 'Salerno', 'Salerno Province', 'Taranto',
        'Naples Province', ' La Libertad', 'Sago Prefecture', 'Savona',
        'Southern Province', 'Jakarta Harbour', 'Singapore Harbor',
        'Calabria', 'Shatt-el-Arab River', 'Shatt-al-Arab River',
        'Tamaulipas', 'Calvados Archipelago', 'Shat-Al-Arab River',
        'Between Kwajalein Atoll & Johnston Island', 'Attica',
        'Adana Province', 'Bandar Ma\x92shur sea inlet', 'Saipan',
        'Carpathian Sea', 'Kwajalein', 'Dar-es-Salaam ',
        '"Head of the Gulf"', 'Ryukyu', ' North Carolina',
        'In transit between Tinian and Leyte', 'Northern Java', 'Tel Aviv',
        'Colon Province', '300 miles east of Luzon',
        'Bernardino Strait near Gulf of Leyte',
        'Off Samar Island in the Gulf of Leyte',
        'Lake Nicaragua (fresh water)', 'Pacific Ocean',
        'Near the Fiji Islands', '40 miles south of Naples ',
        'Northwest of Papua New Guinea', 'Between Hawaii and U.S.A.',
        'Off South American coast', 'Makora-Ulawa Province',
        '04.05N-13.23W', 'Midway Atoll',
        '300 miles east of St. Thomas (Virgin Islands)',
        'West of Ceylon (Sri  Lanka)', 'East Java', 'Camiguin Island',
        'Cay Sal Bank', '(Southwestern Pacific)', 'Panama City',
        'Off Libya', 'North of Pernambuco, Brazil', 'Off coast of Ecuador',
        'Trelawney Province', 'In Convoy OB 274', 'New Georgia',
        'Panama Bay (Pacific Ocean)', 'Bwagaoia', 'Western Papuan Gulf',
        'Torres Strait ', 'Carabobo', 'Ascension Bay', 'North China',
        'Lower San Juan River', 'Nicoya Peninsula', 'Basrah City',
        'West Bengal', 'Queensland ', 'Argyllshire', 'Arran', 'Argyll',
        'Fishing Grounds', 'Newfoundland', 'Isle of Wight',
        'Makira-Uluwa Province', 'Northern (Oro) Province', 'Herzliyah',
        'Elqui Province', 'Istanbul', 'St Michael Parish',
        'Barlavento Islands', 'Viti Levu Island', 'Bay of Fundy', 'Manila',
        'French Southern Territories', 'Niua ', 'Black River',
        'Phoenix Islands', 'Cienfuegos Province', 'Valencia',
        'Santiago Island', 'Near Puntarenas', 'Porto Seguro',
        'Salinas Bay', 'Golfo di Genova in the Ligurian Sea',
        'Sants-Montjic', 'South of the Equator ', 'Bay of Monaco',
        'Valencia ', 'Vancouver',
        '2 to 3 miles off Taboguilla Island, Pacific Ocean', 'Dorset',
        '150 miles offshore', 'Galica', 'Demerara County', 'Vera Cruz',

Cambiad el nombre de las columnas para que todas estÃ©n en minÃºsculas y reemplazad los espacios por _.

In [17]:
columnas_nuevas = {col :  col.lower().replace(' ','_') for col in df.columns}
columnas_nuevas

{'Unnamed: 0': 'unnamed:_0',
 'Case Number': 'case_number',
 'Year': 'year',
 'Type': 'type',
 'Country': 'country',
 'Area': 'area',
 'Location': 'location',
 'Activity': 'activity',
 'Name': 'name',
 'Sex ': 'sex_',
 'Age': 'age',
 'Time': 'time',
 'Species ': 'species_',
 'Investigator or Source': 'investigator_or_source',
 'pdf': 'pdf',
 'href formula': 'href_formula',
 'href': 'href',
 'Case Number.1': 'case_number.1',
 'Case Number.2': 'case_number.2',
 'original order': 'original_order',
 'Unnamed: 22': 'unnamed:_22',
 'Unnamed: 23': 'unnamed:_23'}

In [18]:
df.rename(columns = columnas_nuevas, inplace = True)
df.columns

Index(['unnamed:_0', 'case_number', 'year', 'type', 'country', 'area',
       'location', 'activity', 'name', 'sex_', 'age', 'time', 'species_',
       'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number.1', 'case_number.2', 'original_order', 'unnamed:_22',
       'unnamed:_23'],
      dtype='object')

Eliminad las columnas de Unnamed: 22 y Unnamed: 23, Case Number.1, Case Number.2, original order, Investigator or Source, pdf, href formula.

In [19]:
df_eliminar = df.drop(["unnamed:_22", "unnamed:_23", "case_number.1", "case_number.2", "original_order", "investigator_or_source", "pdf", "href_formula"], axis = 1)

In [20]:
df_eliminar.head()

,unnamed:_0,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1,1,2018.06.18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2,2018.06.09,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
3,3,2018.06.08,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
4,4,2018.06.04,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...

Establece la columna Case Number como Ã­ndice del DataFrame.

In [21]:
df_eliminar.set_index(["case_number"], inplace = True)

In [22]:
df_eliminar

,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,,
2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.06.18,1,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.06.09,2,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.06.08,3,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.06.04,4,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1804.02.26.R,6127,1804.0,Boat,AUSTRALIA,New South Wales,"Georges Head, off Port Jackson",NaN,boat,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
1803.05.17,6128,1803.0,Sea Disaster,USA,South Carolina,Off Charleston,NaN,Captain Jones,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
1803.03.00,6129,1803.0,Unprovoked,AUSTRALIA,Western Australia,"Hamelin Harbour, at Faure Island",NaN,M. Lefevre & a sailor (rescuer),M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
1802.04.13.R,6130,1802.0,Unprovoked,INDIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
1801.12.18.R,6131,1801.0,Provoked,NaN,NaN,NaN,Standing on landed shark's tail,Stephen Pettigew,N,NaN,NaN,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...

In [26]:
df_eliminar.columns

Index(['unnamed:_0', 'year', 'type', 'country', 'area', 'location', 'activity',
       'name', 'sex_', 'age', 'time', 'species_', 'href'],
      dtype='object')

Guarda el csv que no tiene esas columnas para seguir usÃ¡ndolo maÃ±ana.

In [23]:
df_eliminar.to_csv("attack_pair.csv")

In [25]:
df = pd.read_csv('attack_pair.csv')
df.head()

,case_number,unnamed:_0,year,type,country,area,location,activity,name,sex_,age,time,species_,href
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2018.06.18,1,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2018.06.09,2,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2018.06.08,3,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2018.06.04,4,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...